version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./src:/opt/hedgehog/src
     - ./public:/opt/hedgehog/public
     - ./package.json:/opt/hedgehog/public.json
  